### PR TITLE
Support ICS and JellyBean

### PR DESCRIPTION
**Pull request by pylerSM**

### CODE REVIEW

**Comment by hamzahrmalik** [comment]
Has this been tested?

**Comment by pylerSM** [comment]
Yes, it was.
Google Clock is for 4.4 and up.

**Comment by hamzahrmalik** [comment]
Going to close this and not merge, because I've already got my own implementation (based on yours), thanks

**Comment by pylerSM** [comment]
ok

**Comment by hamzahrmalik** [comment]
Also this doesnt seem to work on anything below 4.4

**Comment by hamzahrmalik** [comment]
Looks like in 4.2 (EDIT: and in every other version 4.0-4.3), there are parameters for the dismiss method, see here http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android-apps/4.2.2_r1/com/android/deskclock/AlarmAlertFullScreen.java?av=f#258

**Comment by pylerSM** [comment]
Because of this I used hookAllMethods api so we dont have to do findAndHookMethod for so many android versions.

**Comment by hamzahrmalik** [comment]
Oh yeah didn't notice that

**Pull request closed without merging**
