### PR TITLE
Enable for KitKat

### PR DESCRIPTION
**Pull request by pylerSM**

### CODE REVIEW

**Comment by hamzahrmalik** [comment]
I'm sure you have but I gotta check, have you tested it actually work on kitkat?

**Comment by pylerSM** [comment]
I checked only KK sources.

**Comment by hamzahrmalik** [comment]
OK, I'll test myself in a second, my phone's gone a little haywire right now

**Comment by hamzahrmalik** [comment]
It does work on kitkat yay

**Pull request merged**
